### ISSUE TITLE
Use drop shadow when overriding frame

### ISSUE THREAD

**Issue by LindyBalboa** [willbelr/qtpad#2]
First of, thanks for a nice light-weight common language/framework solution to this app.

Currently when using the "Frameless Option" stacked sticky notes can look like one big blob. There only needs to be a very slight drop shadow for this to look better. Perhaps allow it to be a config option. I know many people don't like their notes stacked, but sometimes it happens and the result is rather glaring.

![image](https://user-images.githubusercontent.com/20605205/40587173-dfae8f5c-61cb-11e8-93e2-bd0d84030728.png)

**Comment by willbelr** [comment]
Thanks for your suggestion. I added a paint event that draw a one pixel border in frameless mode. The color will match background-color value of QLabel#titleLabel. The fix will be part of the next major release, in about a week or so :)
